#### Dataset parameters
dataname: "datasetHH_test1.mat"
split: 1600
batch_size: 100
#### Architecture parameters
scaling: "Default" # Default, Gaussian, or Mixed
weights_norm: "Xavier" # Xavier or Kaiming
adapt_actfun: False
scheduler: "StepLR"
Loss: "mse" # mse or L2
epochs: 10000
lr: 0.001
u_dim: 3 # Input dimension for Branch Net
x_dim: 1 # Input dimension for Trunk Net
G_dim: 50 # Output dimension
inner_layer_b: [50, 50, 50, 50]
inner_layer_t: [50, 50, 50, 50]
activation_b: "Tanh"
activation_t: "Tanh"
arc_b: "FNN_BN"
arc_t: "FNN_BN"
initial_b: "Glorot normal"
initial_t: "Glorot normal"
#### FNO parameters
fun_actFNO: "ReLu"
scalar: "Real"
arc: "Classic"
L: 4
d_v: 1
modes: 32
#### Plotting and tensorboard
ep_step: 20
idx: [7, 42, 45, 15] # random test sample
plotting: False
