#### default_params
#### Dataset hyper-parameters
DataPath: "datasetHH_test1.mat"
ntot: 2000
ntrain: 1600
ntest: 400
s: 1 # subsampling parameter

#### Training hyper-parameters
retrain: 42
epochs: 20000
lr: 0.001
batch_size: 100
Loss: "L2" # "L2", "H1", "mse"
weight_decay: 0.0001 # = 1e-4
scheduler: "StepLR"
step_size: 1000
gamma: 0.8 # multiply the lr every step_size

#### Architecture hyper-parameters
u_dim: 500 # Input dimension for Branch Net
x_dim: 1 # Input dimension for Trunk Net
N_FourierF: 0 # number of Fourier features to add in the Trunk Net
G_dim: 500 # Output dimension
exp_G: 0 # 0, 0.5, 1, 1.5
inner_layer_b: [500, 500, 500]
inner_layer_t: [500, 500, 500]
activation_b: "Tanh" # 'relu', 'gelu', 'tanh', 'sin', 'leaky_relu', 'sin', 'sigmoid'
activation_t: "Tanh"
arc_b: "FNN" # 'FNN', 'FNN_BN'
arc_t: "FNN"

#### Plotting and tensorboard
ep_step: 100
idx: [7, 42, 93, 158] # random test sample
plotting: False
