#### NEW DEFAULT PARAMS FILE. We have now dataset_train and dataset_test
#### instead of dataname and split
#### Dataset parameters
#dataname: "datasetHH_test1.mat"
#split: 1600
#dataset_train: ["dataset/datasetHH_test_0peaks.mat",
#                "dataset/datasetHH_test_1peaks.mat",
#                "dataset/datasetHH_test_2peaks.mat",
#                "dataset/datasetHH_test_3peaks.mat",
#                "dataset/datasetHH_test_4peaks.mat",
#                "dataset/datasetHH_test_5peaks.mat",
#                "dataset/datasetHH_test_6peaks.mat"]
#dataset_test: ["dataset/datasetHH_test_0peaks_test.mat",
#                "dataset/datasetHH_test_1peaks_test.mat",
#                "dataset/datasetHH_test_2peaks_test.mat",
#                "dataset/datasetHH_test_3peaks_test.mat",
#                "dataset/datasetHH_test_4peaks_test.mat",
#                "dataset/datasetHH_test_5peaks_test.mat",
#                "dataset/datasetHH_test_6peaks_test.mat"]
arc: "FNO"
level: 6
width: 48
dataset_train: "dataset/datasetHH_test1_train.mat" 
dataset_test: "dataset/datasetHH_test1_test.mat"
labels: False
full_v_data: True
N_FourierF: 10   
scale_FF: 1
batch_size: 100
#### Architecture parameters
scaling: "None" # Default, Gaussian, Mixed or Fourier
weights_norm: "Xavier" # Xavier or Kaiming
adapt_actfun: False
scheduler: "StepLR"
Loss: "L2" # mse or L2
epochs: 10000
lr: 0.001
u_dim: 3 # Input dimension for Branch Net
x_dim: 1 # Input dimension for Trunk Net
G_dim: 500 # Output dimension
inner_layer_b: [500, 500, 500, 500]
inner_layer_t: [500, 500]
activation_b: "Tanh"
activation_t: "Tanh"
arc_b: "FNN_LN"
arc_t: "AdaptFF"
initial_b: "Glorot normal"
initial_t: "Glorot normal"
#### FNO parameters
d_a            : 2 
d_v            : 32
d_u            : 1
L              : 4
modes          : 16
act_fun        : "ReLu"
initialization : "Kaiming"
scalar         : "Real" 
padding        : True
arc_fno        : "Classic"
x_padding      : 10
RNN            : True 
#### Plotting and tensorboard
ep_step: 20
idx: [7, 42, 45, 15] # random test sample
plotting: False