#### EXAMPLE OF yml FILE FOR WAVELET NEURAL OPERATOR
#### Dataset parameters
dataset_train: "dataset/datasetHH_test1_train.mat" 
dataset_test: "dataset/datasetHH_test1_test.mat"
labels: False
full_v_data: True
batch_size: 100
# WNO parameters
arc: "WNO"
level: 6
width: 48
#### Architecture parameters
scaling: "None" # Default, Gaussian, Mixed or Fourier
scheduler: "StepLR"
Loss: "L2" # mse or L2
epochs: 2000
lr: 0.001
#### Plotting and tensorboard
show_every: 1 # epochs. Also saves on TensorboardX 
ep_step: 20
idx: [7, 42, 45, 78] # random test sample
plotting: False